# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_RxBert', [dirname(__file__)])
        except ImportError:
            import _RxBert
            return _RxBert
        if fp is not None:
            try:
                _mod = imp.load_module('_RxBert', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _RxBert = swig_import_helper()
    del swig_import_helper
else:
    import _RxBert
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class RxBert(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RxBert, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RxBert, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _RxBert.new_RxBert(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _RxBert.delete_RxBert
    __del__ = lambda self : None;
    def check(self, *args): return _RxBert.RxBert_check(self, *args)
    def resetState(self): return _RxBert.RxBert_resetState(self)
    def setPN(self, *args): return _RxBert.RxBert_setPN(self, *args)
    def getPN(self): return _RxBert.RxBert_getPN(self)
    def getBitsRX(self): return _RxBert.RxBert_getBitsRX(self)
    def getBitsRXinSync(self): return _RxBert.RxBert_getBitsRXinSync(self)
    def getErrors(self): return _RxBert.RxBert_getErrors(self)
    def synced(self): return _RxBert.RxBert_synced(self)
    def getSyncLossCount(self): return _RxBert.RxBert_getSyncLossCount(self)
RxBert_swigregister = _RxBert.RxBert_swigregister
RxBert_swigregister(RxBert)

# This file is compatible with both classic and new-style classes.


